### ISSUE TITLE
June 2022 Contribution - Algem Indonesia (Robin)

### ISSUE THREAD

**Issue by AlgemIndonesia** [AlgemDeFi/Algyors-Program#8]
**Discord Username** : Robin58#0059
**Twitter Username** : @Algem_Indonesia
**EVM Wallet Addres** : 0xE97B47D88d7071Ddc107EA7039Ae388698Da504D

**Contribution :**
1. Community Management
- Active on Discord Server #ID-Indonesia
![151c9e33-09dd-4297-b043-e6b89ebe072c](https://user-images.githubusercontent.com/107385646/182676733-d43ceec5-6256-4735-b436-f5dc038daa71.jpg)

- Update on Twitter Local https://twitter.com/Algem_Indonesia
![e777aedd-e036-4c8f-a59b-91431c85a1a2](https://user-images.githubusercontent.com/107385646/182677520-337c87e9-1695-4574-943d-d50fb2bdf0a7.jpg)

2. VSM
- https://medium.com/@Algem_Indonesia/kampanye-algem-testnet-df536029d3d9
- https://medium.com/@Algem_Indonesia/hasil-kampanye-testnet-resmi-pertama-algem-luar-biasa-7f5c81f26137

3. The Professor
- https://app.gitbook.com/o/yLbh5uTvpdM2cDCsrqs3/home ( Link Has Broke Because Not Upgrade To Premium)
![8442a599-1074-4923-8547-ad89245651da](https://user-images.githubusercontent.com/107385646/182678423-f688dccc-66ec-408d-809a-f8c7597bea84.jpg)

**Comment by Gunit2481** [comment]
Hi Robin,

Thank you for submitting your work for June. Points were added to the spreadsheet.

Concerning your Professor task, I can't take it into consideration because I can't see what work you did in the Library. Didn't you upload it somewhere else like on Medium?

![image](https://user-images.githubusercontent.com/85451570/184380083-a3feefcf-300b-458f-93f9-fb53f25a01fc.png)
